### ISSUE TITLE
Immediate crash on startup

### ISSUE THREAD

**Issue by gvoysey** [seebye/chameleon#5]
#  Installation 
`pipx install moving-chameleon`

#  Version information 
Python 3.6.3
docopt==0.6.2
moving-chameleon==4
Pillow==6.1.0
python3-xlib==0.15

# Steps to reproduce
Launch `chameleon` with no arguments

# What happens
```
> chameleon                        
Traceback (most recent call last):
  File "/home/gvoysey/.local/bin/chameleon", line 11, in <module>
    load_entry_point('moving-chameleon==4', 'console_scripts', 'chameleon')()
  File "/home/gvoysey/.local/pipx/venvs/moving-chameleon/lib/python3.6/site-packages/chameleon/chameleon.py", line 131, in main
    (ui.get_pixel(root, x, y),), rgbs))
  File "/home/gvoysey/.local/pipx/venvs/moving-chameleon/lib/python3.6/site-packages/chameleon/ui.py", line 93, in get_pixel
    return PIL.Image.frombytes("RGB", (1, 1), image.data, "raw", "BGRX")\
  File "/home/gvoysey/.local/pipx/venvs/moving-chameleon/lib/python3.6/site-packages/PIL/Image.py", line 2546, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/gvoysey/.local/pipx/venvs/moving-chameleon/lib/python3.6/site-packages/PIL/Image.py", line 830, in frombytes
    s = d.decode(data)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by seebye** [comment]
I think it was an issue with the dependency "python**3**-xlib".  
I released an update on pypi/pip which uses python-xlib instead of python**3**-xlib.  
So it should be fixed by:

1. making sure python**3**-xlib isn't installed anymore:  
`pip uninstall moving-chameleon python3-xlib -y`
2. install the update:  
`pip install --no-cache-dir -U moving-chameleon`  
3. [If python-xlib was already installed it could lead to an import error claiming that some module doesn't exist.  
E.g. ImportError: cannot import name 'X' from 'Xlib' (unknown location)
(Pip doesn't seem to handle with multiple packages with the same module name well.)  
This is easily solveable by uninstalling python-xlib and reinstalling it.  
`pip uninstall python-xlib -y; pip3 install python-xlib` ]

**Comment by gvoysey** [comment]
I confirm this resolves my issue.  Thanks for the very prompt response!  I'll close this.
